### ISSUE TITLE
Add colors for buttons

### ISSUE THREAD

**Issue by znanywawa** [usernein/tv-card#17]
**Is your feature request related to a problem? Please describe.**
I do love this card, but I think that it would be a great idea to add ability to add colors for some buttons.

**Describe the solution you'd like**
Mostly I am thinking about RED, GREEN, YELLOW, CYAN buttons where such color brings easy identify what kind of button are we using (of course, all those buttons on another row ubt already I gave a FR for additional custom rows).

**Describe alternatives you've considered**
I didnt as this card is overal great but I think that such improvement for buttons collors would be great.

**Comment by roumano** [comment]
i would, also, like to have this enhancement 
ideally also able to set the colors via templating

example of my own tv-card (based with only custom:button-card ) for power icon :  
```
type: custom:button-card
icon: mdi:power
styles:
  icon:
    - color: |
          [[[
            if (states['sensor.tv_power'].state > 10)
              return 'orange';
            else
            return 'green';
          ]]]
```

**Comment by solid-pixel** [comment]
@roumano @znanywawa FYI it's possible to change the  icons' color with the help of [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod):

```yaml
type: custom:tv-card
entity: media_player.android_tv
card_mod:
  style:
    ha-icon-button:
      .: |
        ha-icon-button[title='power'] {
          {% if states('media_player.android_tv_192_168_0_100') in ['off', 'unknown', 'unavailable'] %}          
            opacity: .3;
          {% else %}
            color: red;
          {% endif %};
        }

...
```
replace `power` with the button's title, you can find it by inspecting it with your browser's devtools:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/18260178/210135612-af800296-2598-44b5-bf82-6c56aef294c2.png">
