### ISSUE TITLE
TV Card does not power on TV

### ISSUE THREAD

**Issue by happyhammer7** [usernein/tv-card#18]
I am running the current latest release but seem to have a strange issue. The TV card works great on both my Samsung TVs. However, neither card I have set up for them will turn the TVs on (will turn it off though).

I have no other integrations for the TVs installed and the power toggle works 100% of the time directly inside the Samsung TV integration by ollo69. I have tried changing some of the settings in the TV integration such as the method used to turn the TV on etc but these changes have no impact within the tv card itself

**Comment by GrubyRabbit** [comment]
Same here. Only "off" works.

**Comment by antonio1475** [comment]
Have you tried
```
        custom_keys:
          power:
            icon: mdi:power
            service: media_player.toggle
            service_data:
              entity_id: media_player.samsungtv_smart
```

?
This will call ollo69's integration toggle. I have it like this
