### ISSUE TITLE
Touchpad key return doesnt use custom keys

### ISSUE THREAD

**Issue by jtfowler22** [usernein/tv-card#20]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v0.5.2

Android

Using custom keys I changed the "up,down,left,right,enter" to work with my tv. (im using the remote.send_command).  Works GREAT!  Was able to redefine all the buttons i wanted and it works for my sony bravia.... EXCEPT FOR the touchpad.

I was looking at the tv-card.js file and it looks like once the code determines where I went on the touchpad (for example if i go left) it just sends the KEY for "left".  But I get an error saying media / media_player isnt available on my device.  Is the touchpad code routing the keys through a different function and not using custom_keys like the rest of the buttons?

**Comment by Rocologo** [comment]
I have the same problem. It does not work for the navigation_row and either not for volume_row. The slider does unfortunately not work with my old Samsung TV.

```
type: custom:tv-card
entity: media_player.samsung_tv
title: Samsung TV
power_row:
  - tv_power
channel_row:
  - tv_sound_down
  - tv_sound_up
  - tv_sound_mute
apps_row:
  - tv_hdmi1
  - tv_hdmi3
  - tv_navigation_smart
source_row:
  - return
  - home
  - tv_navigation_left
  - tv_navigation_right
  - tv_navigation_ok
  - tv_navigation_up
  - tv_navigation_down
  - tv_navigation_return
  - tv_navigation_exit
media_control_row:
  - tv_player_back
  - tv_player_play
  - tv_player_pause
  - tv_player_forward
custom_keys:
  tv_power_on:
    icon: mdi:power-on
    service: script.tv_power_on
  tv_power_off:
    icon: mdi:power-off
    service: script.tv_power_off
  tv_power:
    icon: mdi:power
    service: script.tv_power_toggle
  tv_sound_up:
    icon: mdi:volume-plus
    service: script.tv_sound_up
  tv_sound_down:
    icon: mdi:volume-minus
    service: script.tv_sound_down
  tv_sound_mute:
    icon: mdi:volume-mute
    service: script.tv_sound_mute
  tv_hdmi1:
    icon: mdi:cast
    service: script.tv_hdmi1
  tv_hdmi3:
    icon: mdi:kodi
    service: script.tv_hdmi3
  tv_player_play:
    icon: mdi:play
    service: script.tv_player
  tv_player_pause:
    icon: mdi:pause
    service: script.tv_player_pause
  tv_player_back:
    icon: mdi:rewind
    service: script.tv_player_back
  tv_player_forward:
    icon: mdi:fast-forward
    service: script.tv_player_forward
  tv_navigation_ok:
    icon: mdi:checkbox-blank-circle
    service: script.tv_navigation_ok
  tv_navigation_up:
    icon: mdi:chevron-up
    service: script.tv_navigation_up
  tv_navigation_down:
    icon: mdi:chevron-down
    service: script.tv_navigation_down
  tv_navigation_left:
    icon: mdi:chevron-left
    service: script.tv_navigation_left
  tv_navigation_right:
    icon: mdi:chevron-right
    service: script.tv_navigation_right
  tv_navigation_smart:
    icon: mdi:application
    service: script.tv_navigation_right
  tv_navigation_return:
    icon: mdi:keyboard-return
    service: script.tv_navigation_return
  tv_navigation_exit:
    icon: mdi:exit-run
    service: script.tv_navigation_exit

```
![image](https://user-images.githubusercontent.com/1008133/189493144-259c8599-bf73-4e5f-b23f-c588ceba26ea.png)
