### ISSUE TITLE
How to have a HBO Max icon?

### ISSUE THREAD

**Issue by Stooovie** [usernein/tv-card#3]
I tried "HBO Max", "hbomax" and various other permutations, to no avail. Any idea how to set up a HBO Max button? Thanks!

Thanks for the fantastic addon card BTW!

**Comment by usernein** [comment]
Hmmm nice request
It's not possible right now because the card only accept icons from MaterialDesign and HBO Max doesn't exist there

I have plans to add support to any icon available for HASS in future updates, but rn i don't know how to do it :p 

But i know how to make it support custom svg paths for icons and i guess i can make it fast since the original tv-card did it for Prime Video

BTW i did not find an icon for HBO Max, only for [HBO at SimpleIcons](https://simpleicons.org/?q=hbo)

**Comment by usernein** [comment]
Done! @Stooovie check the [v0.4.1](https://github.com/usernein/tv-card/releases/tag/v0.4.1) release :)

**Comment by Stooovie** [comment]
Oh, I am sorry, this is a very cool feature (how do you guys work so fast?) but I haven't been clear - what I wanted was the button for switching into the HBO Max app. "spotify" or "netflix" are simple but I can't get HBO Max app to show up in the card. It's probably a question for the Samsung TV integration devs but I haven't found it looking through their docs. 

Thanks!

**Comment by usernein** [comment]
Ahhh, got it! Even if i got it wrong before, a cool feature was born anyway :v

Spotify, Netflix and Youtube are currently the only sources defined in the code [here](https://github.com/usernein/tv-card/blob/ca22e6d72f87ae2c20d5d4dd3ca12a6d3107769a/tv-card.js#L30-L34).
So, without customizing, you can only use these. The good news are that customizing is (most of the time) very easy.

In order to add a button for any source that is not defined in the code, you need to define it as custom source at the card config:

```yaml
custom_sources:
  <button_name>:
    icon: <icon_name>
    source: <app_id>
```

This is the way to go if you're using Samsung with [ha-samsungtv-smart](https://github.com/ollo69/ha-samsungtv-smart), like me.
In your case, you also need to define an icon and get the app_id for HBO Max
And i hope you're using Samsung, because i got the app_id from mine and it's easier to make it work using this ointegration.

If you're not using Samsung, your custom button should have a service calling the right method on the integration you use:

```yaml
custom_sources:
  <button_name>:
    icon: <icon_name>
    service: <domain>.<service>
    service_data:
        <params>
````

I managed to make a HBO Max button for my Samsung TV with some settings into the integration and this config into the card config:
```yaml
apps_row:
  - netflix
  - youtube
  - spotify
  - hbomax
custom_sources:
  hbomax:
    icon: hbo
    source: HBO Max
custom_icons:
  hbo: >- # from SimpleIcons
    M7.042 16.896H4.414v-3.754H2.708v3.754H.01L0
    7.22h2.708v3.6h1.706v-3.6h2.628zm12.043.046C21.795 16.94 24 14.689 24
    11.978a4.89 4.89 0 0 0-4.915-4.92c-2.707-.002-4.09 1.991-4.432
    2.795.003-1.207-1.187-2.632-2.58-2.634H7.59v9.674l4.181.001c1.686 0
    2.886-1.46 2.888-2.713.385.788 1.72 2.762 4.427 2.76zm-7.665-3.936c.387 0
    .692.382.692.817 0 .435-.305.817-.692.817h-1.33v-1.634zm.005-3.633c.387 0
    .692.382.692.817 0 .436-.305.818-.692.818h-1.33V9.373zm1.77
    2.607c.305-.039.813-.387.992-.61-.063.276-.068 1.074.006
    1.35-.204-.314-.688-.701-.998-.74zm3.43 0a2.462 2.462 0 1 1 4.924 0 2.462
    2.462 0 0 1-4.925 0zm2.462 1.936a1.936 1.936 0 1 0 0-3.872 1.936 1.936 0 0 0
    0 3.872Z
```

In the integration settings you need to add HBO Max manually into the source list using the app_id. I did it in the configuration.yaml:
```yaml
samsungtv_smart:
  - host: <ip_of_tv>
    app_list: '{"Netflix": "org.tizen.netflix-app", "YouTube": "111299001912", "Spotify": "3201606009684", "HBO Max": "cj37Ni3qXM.HBONow"}'
```

I got the HBO Max app_id in Developer Tools, checking the attributes of the tv entity while HBO Max was open on the tv.
I manually set app_list but i read that if you don't set it, the integration will try to load all available apps at startup. It didn't work for me, that's why i set manually.
Feel free to test if the button already works without changing configuration.yaml (
if you actually don't set anything manually)

If even after changing configuration.yaml (and restarting Home Assistant) the button doesn't work, you might try to get the app_id by yourself in Developer Tools (i don't know if the app_ids are always the same on all models)

Please tell me if it works :)
