### ISSUE TITLE
Volume buttons

### ISSUE THREAD

**Issue by 1iverea9er** [usernein/tv-card#7]
How to configure the execution of castom service for each button (volume_up, volume_down, volume_mute) ???
Вefault service does not work.

p.s. and same problem for 'navigation_row'

**Comment by usernein** [comment]
@1iverea9er it's documented on [Custom buttons](https://github.com/usernein/tv-card#custom-buttons)

**Comment by 1iverea9er** [comment]
I really don't understand how to do this.  I tried the following code in card section
...
>               volume_row:
>                   - vlm_down
>                   - mute
>                   - vlm_up
....

and following code in 'custom_keys'  :
....

>                   vlm_down:
>                     icon: mdi:volume-minus
>                     service: media_player.volume_down
>                     target:
>                       entity_id: media_player.sony_bravia_tv
>                   mute:
>                     icon: mdi:volume-mute
>                     service: media_player.volume_mute
>                     target:
>                       entity_id: media_player.sony_bravia_tv
>                   vlm_up:
>                     icon: mdi:volume-plus
>                     service: media_player.volume_up
>                     target:
>                       entity_id: media_player.sony_bravia_tv

....

<img width="378" alt="image" src="https://user-images.githubusercontent.com/82063500/179066978-4135ecc1-d8ee-4bd8-be9a-cdf894deb37b.png">

What am I doing wrong ?

**Comment by rafalpetryka** [comment]
@1iverea9er you should try
```volume_row: buttons```
and custom keys like this
```
volume_down:
  icon: mdi:volume-minus
  service: media_player.volume_down
  target:
    entity_id: media_player.sony_bravia_tv
volume_mute:
  icon: mdi:volume-mute
  service: media_player.volume_mute
  target:
    entity_id: media_player.sony_bravia_tv
volume_up:
  icon: mdi:volume-plus
  service: media_player.volume_up
  target:
    entity_id: media_player.sony_bravia_tv
```

Then it should works fine ;)
